### ISSUE TITLE
JSON handling

### ISSUE THREAD

**Issue by rdh** [rdh/active_intelligence#21]
- [ ] Document OpenAI config for JSON
- [ ] Convenience method(s) for handling JSON responses

**Comment by rdh** [comment]
```
json:
  <<: *openai
  response_format:
    type: json_object

```
